### ISSUE TITLE
Last deleted <li> do not get removed from the "data-simple-tags" attribute

### ISSUE THREAD

**Issue by HymedGh** [kurtobando/simple-tags#4]
![image](https://user-images.githubusercontent.com/69634614/111474143-078e2900-872c-11eb-8b95-7e650e17daa2.png)

**Comment by kurtobando** [comment]
Hello @HymedGh,

Thank you for checking "simple-tags" repository, and letting me know this bug. Will check this out later today, and commit the solution.

**Comment by kurtobando** [comment]
Hello @HymedGh,

Reported bug has been fix in `commit 82b0f0e28ccc8c87d8c4a1bb5188902c7153a83c` . Thank you for the reported bug.

**Comment by HymedGh** [comment]
Hey @kurtobando ,

Thx for solving this quick the reported issue.
Can you please let us know where in your code, the fix was made ?
I looked through twice, but wasn't able to identify it  :/

Thank u for sharing your code btw ! Your function helped me a lot to create this :

![image](https://user-images.githubusercontent.com/69634614/111584516-3ead1a80-87be-11eb-9af1-7e068a5167aa.png)

**Comment by kurtobando** [comment]
@HymedGh 
You are welcome. Here are the changes i made. 
`https://github.com/kurtobando/simple-tags/commit/82b0f0e28ccc8c87d8c4a1bb5188902c7153a83c`

I move the line 34 to 36 in 
`source/script/script.js `
